### ISSUE TITLE
Performance in AVs scenes

### ISSUE THREAD

**Issue by Toytiny** [haoy945/DeMF#1]
Great work. Did you evaluate the proposed method in the autonomous vehicle scenes? By the way, which conference will this paper be published in?

**Comment by haoy945** [comment]
Thanks! We haven't evaluate  in the autonomous vehicle scenes yet. But we believe that the proposed method is also effective for these scenarios.
Unfortunately, our paper was rejected by ECCV2022, and we will not submit to other conferences in the future. But in any case, we hope that our method can inspire others.
