### ISSUE TITLE
Why conduct experiment on SUNRGB-D dataset only?

### ISSUE THREAD

**Issue by Agito555** [haoy945/DeMF#10]
I am a beginner, and perhaps this is a simple question. I noticed that the experiments in the article were conducted on SUNRGB-D, rather than, like other articles, on both SUNRGB-D and Scannet-V2. As far as I know, Scannet-V2 also has images. Could you please explain what differences between these two datasets led to conducting experiments on SUNRGB-D instead of Scannet-V2?

**Comment by chenshi3** [comment]
The point in scannet is complete and  does not necessitate extensive visual assistance.

**Comment by Agito555** [comment]
Thanks.
