### ISSUE TITLE
I cannot find ClassAgnosticBBoxCoderGFReg in your DeMF repository

### ISSUE THREAD

**Issue by Chuxwa** [haoy945/DeMF#2]
Thanks for sharing so nice work DeMF. However, I cannot find ClassAgnosticBBoxCoderGFReg of in your DeMF repository. ClassAgnosticBBoxCoderGFReg is the bbox coder of your model, which appears on the line 98 of the "configs/demf/demf_votenet.py". I want to know whether you will release this part code.

**Comment by haoy945** [comment]
Thanks for your question. It seems that I forgot to update the config, and I have now fixed this bug.
